site_name: Fosshost Docs
theme:
  name: material
  logo: /assets/favicon.png
  favicon: /assets/favicon.png
  custom_dir: overrides
  features:
    - navigation.instant
  palette:
    - media: "(prefers-color-scheme: light)" 
      scheme: default
      primary: red
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)" 
      scheme: slate
      primary: red
      toggle:
        icon: material/weather-night
        name: Switch to light mode



repo_name: fosshostorg/public-docs
repo_url: https://github.com/fosshostorg/public-docs
edit_uri: https://github.com/fosshostorg/public-docs/edit/main/docs/
markdown_extensions:
  - toc:
      permalink: true
  - md_in_html
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences 
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg



copyright: Content is available under the Public Domain, by Fosshost.
plugins:
    - search
    # NOTE: Because of an upstream bug, redirects won't work on Windows.
    # Luckily, it works perfectly on other filesystems and redirects aren't a critical feature
    - redirects:
        redirect_maps:
            # Products and services
            'en/home/mirrors-as-a-service.md': 'products-and-services/mirrors-as-a-service.md'
            'en/home/aarch64-virtual-private-server.md': 'products-and-services/aarch64-virtual-private-server.md'
            'en/home/virtual-private-server.md': 'products-and-services/virtual-private-server.md'
            'en/home/domain-reg-management.md': 'products-and-services/domain-reg-management.md'
            # About
            'en/home/financial-information.md': 'about/financial-information.md'
            'en/home/team.md': 'about/team.md'
            'en/home/hosting-sponsors.md': 'about/hosting-sponsors.md'
            'en/home/support.md': 'about/support.md'
            'en/home/mutual-respect-policy.md': 'about/mutual-respect-policy.md'
            'en/home/volunteering-opportunities.md': 'about/volunteering-opportunities.md'
            # Features
            'en/home/change-request.md': 'features/change-request.md'
            'en/home/service-features.md': 'features/service-features.md'
            # General
            'en/home/application.md': 'general/application.md'
            'en/home/getting-started.md': 'general/getting-started.md'
            'en/home/how-can-you-help.md': 'general/how-you-can-help.md'
            'en/home/regions.md': 'general/regions.md'
            'en/home/what-do-we-expect.md': 'general/what-do-we-expect.md'
            # Howtos
            'en/home/how-to-connect-to-your-virtual-instance.md': 'howtos/how-to-connect-to-your-virtual-instance.md'
            'en/home/configuring-your-new-vps.md': 'howtos/configuring-your-new-vps.md'
            'en/home/how-to-create-ssh-key.md': 'howtos/how-to-create-ssh-key.md'
            'en/home/how-to-lock-down-ssh.md': 'howtos/how-to-lock-down-ssh.md'
            'en/home/how-to-manage-vm.md': 'howtos/how-to-manage-vm.md'


